const names: Record<string, string> = { "zh-CN": "中文", "en-US": "English", "ja-JP": "日本語", "es-ES": "Español", "fr-FR": "Français", "de-DE": "Deutsch" };
export const localeName = (locale: string) => names[locale] ?? locale;
export const brandName = (locale: string) => locale === "zh-CN" ? "嗨！图书馆" : "Hai! Library";
export const copy = {
  "zh-CN": { library: "图书馆", progress: "我的进度", about: "关于", speak: "我会的语言", learn: "我要学习", eyebrow: "多语言分级阅读", intro: "用你熟悉的语言浏览界面与解释，选择另一种语言开始阅读。", intro2: "语言组合可以随时更换。", find: "找一本故事", browse: "浏览图书馆", fit: "找一本适合你的故事", search: "搜索书名、简介、作家或主题", level: "等级", writerStyle: "作家风格", all: "全部", start: "开始阅读", aiGenerated: "内容由 AI 生成" },
  "en-US": { library: "Library", progress: "My progress", about: "About", speak: "I speak", learn: "I am learning", eyebrow: "Multilingual graded reading", intro: "Browse the interface and explanations in a language you know, then choose another language to read.", intro2: "Change the language pair at any time.", find: "Find a story", browse: "Explore the library", fit: "Find a story that fits", search: "Search titles, summaries, writers, or topics", level: "Level", writerStyle: "Writer Style", all: "All", start: "Start reading", aiGenerated: "Content generated by AI" }
} as const;
export function ui(locale: string) { return copy[locale as keyof typeof copy] ?? copy["en-US"] }
